# Generated by Django 6.0.5 on 2026-05-26 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_details', models.CharField(max_length=100)),
                ('job_post', models.CharField(max_length=70)),
                ('job_category', models.CharField(choices=[('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('human_resource', 'Human Resource'), ('information technology', 'Information Technology'), ('business_development', 'Business Development'), ('sales_communication', 'Sales & Communication'), ('teaching_education', 'Teaching & Education')], max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('job_nature', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote/WFH', 'Remote/WFH')], max_length=15)),
                ('job_salary', models.IntegerField(default=1)),
                ('job_published', models.DateTimeField(auto_now=True)),
                ('job_dateline', models.DateField()),
                ('job_desc', models.CharField(max_length=250)),
                ('job_responsibility', models.CharField(max_length=400)),
                ('job_qualification', models.CharField(max_length=400)),
                ('job_vacancy', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=1000)),
                ('applicant_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job_detail')),
            ],
        ),
    ]
